---
title: " "
pagetitle: "Jerred K. Schafer"
---

<link rel="stylesheet" href="styles.css" type="text/css">
<link rel="stylesheet" href="academicicons/css/academicons.min.css"/>

## Research Interests
* Micro- and Macroevolution in Primates and Fossil Hominins
* Quantitative Genetics
* Sexual Selection
* Bayesian Statistics

## Research Funding

2020: Leakey Foundation Doctoral Dissertation Grant. Project: The evolution of sex differences in mandrills (*Mandrillus sphinx*): quantitative genetics of color and size dimorphism.

2020: University at Albany Dissertation Research Fellowship 

2017: University at Albany Graduate Student Association Professional Development Grant

2013: NSF Research Experience for Undergraduates (REU) Fellowship


### Selected publications

**Schafer JK**, Gordon AD, Ngoubangoye B, Charpentier, M.J.E., Setchell JM. (2021). Heritability of secondary sexual characters in mandrills (*Mandrillus sphinx*). *Am Nat*. Submitted.

## Field and Research Experience
* 2020: Orkney & Shetland, Scotland Census Database Researcher
* 2019: Orkney & Shetland, Scotland Census Database Researcher
* 2017: Evolutionary Quantitative Genetics Workshop, Friday Harbor Laboratories, University of Washington
* 2016: Orkney, Scotland Census Database Researcher
* 2015: Orkney, Scotland Census Database Researcher
* 2014: Archaeological Excavation Project at Vanua Levu, Fiji
* 2013: Archaeological Excavation Project at Vanua Levu, Fiji

## Professional Affiliations
* American Association of Physical Anthropologists
* American Society of Naturalists
* Society for the Study of Evolution
* Evolutionary Demography Society


