---
title: " "
pagetitle: "Jerred K. Schafer"
---

<link rel="stylesheet" href="styles.css" type="text/css">
<link rel="stylesheet" href="academicicons/css/academicons.min.css"/>

## Invited

2020 Durham University Evolutionary Anthropology Research Group (EARG) Seminar Series: *Microevolution of secondary sexual characteristics in mandrills*

2019 Clarion University Department of Anthropology Seminar Series: *The evolution of sex differences in mandrills*

## Conference Presentations

2020 American Society of Physical Anthropologist, Online: *Quantitative Genetics of Body Mass and Color in Mandrills*

2019 American Society of Physical Anthropologist, Cleveland, OH: *Response to selection on facial coloration in mandrills*

2018 American Society of Physical Anthropologist, Austin, TX: *Heritability of coloration in Mandrillus sphinx*

2016 Northeastern Evolutionary Primatologist Conference (NEEP), New York, NY: *The relationship between mtDNA substitution parameters and BMR in primates*

2015 American Society of Physical Anthropologist, Atlanta, GA: *Life history variation in strepsirrhine primates from the Duke Lemur Center*

